service: mealogger-api
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
functions:
  getFoods:
    handler: handler.getFoods
    name: ${self:service}-getFoods
    events:
      - http:
          path: foods
          method: get
  getFoodCategories:
    handler: handler.getFoodCategories
    name: ${self:service}-getFoodCategories
    events:
      - http:
          path: food_categories
          method: get
