service: mealogger-api
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USERNAME: ${self:custom.secrets.DB_USERNAME}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
functions:
  getDishes:
    handler: handler.getDishes
    name: ${self:service}-getDishes
    events:
      - http:
          path: dishes
          method: get
  getFoods:
    handler: handler.getFoods
    name: ${self:service}-getFoods
    events:
      - http:
          path: foods
          method: get
  getFoodCategories:
    handler: handler.getFoodCategories
    name: ${self:service}-getFoodCategories
    events:
      - http:
          path: food_categories
          method: get
